### ISSUE TITLE
Cannot read property 'constructor' of null

### ISSUE THREAD

**Issue by mattludwigs** [postcss/postcss#730]
At this line https://github.com/postcss/postcss/blob/master/lib/node.es6#L7

I am running into a situation where `obj` is `null`.

I was not able to build my webpack config due to this error: `Cannot read property 'constructor' of null`

What would cause this to happen and what might the proper fix?

I was able to add this to my local node modules to test

```
 if (obj === null) {
  return {};
}
```

Which I do no think is a good solution, but was able to build my webpack config.

Thank you for any help you maybe able to provide.

**Comment by TrySound** [comment]
@mattludwigs Show your config. This is the problem of plugins not postcss itself.

**Comment by mattludwigs** [comment]
@TrySound here are my loaders:
```
module : {
    noParse : [
      /\.min\.js$/,
      /lodash\/index\.js$/,
      /immutable\/dist\/immutable\.js$/,
      /bluebird\/js\/browser\/bluebird\.js$/,
      /\.json$/,
      /qs\/dist\/qs\.js$/,
    ],
    loaders : [
      {
        test : /\.js$/,
        // eventually, Joi and Hoek will probably ship with browser builds, but
        // until then, they need to run through Babel. once they provide browser
        // builds, then we can change this to be an alias like `qs`
        include : [
          /\/joi\//,
          /\/hoek\//,
        ],
        loader : 'babel',
        query : {
          stage : 0,
          optional : [ 'runtime' ],
          plugins : BUILD_STATIC ? [] : [ 'react-display-name', 'react-transform' ],
          extra : BUILD_STATIC ? {} : {
            'react-transform' : {
              transforms : [{
                transform : 'react-transform-hmr',
                imports : ['react'],
                locals : ['module'],
              }],
            },
          },
        },
      },
      {
        test : /\.jsx|js$/,
        exclude : /node_modules/,
        loader : 'babel',
        query : {
          stage : 0,
          optional : [ 'runtime' ],
          plugins : BUILD_STATIC ? [] : [ 'react-display-name', 'react-transform' ],
          extra : BUILD_STATIC ? {} : {
            'react-transform' : {
              transforms : [{
                transform : 'react-transform-hmr',
                imports : ['react'],
                locals : ['module'],
              }],
            },
          },
        },
      },
      {
        test : /\.json$/,
        loader : 'json',
      },
      {
        test : /\.css$/,
        loader : ExtractTextPlugin.extract('css?sourceMap'),
      },

      // atlas assets
      {
        test : /\.scss$/,
        exclude : [ path.resolve(__dirname, 'lease') ],
        loader : ExtractTextPlugin.extract('css?sourceMap!autoprefixer?browsers=last 3 versions!sass?sourceMap'),
      },
      {
        test : /\.(jpe?g|png|gif|svg|woff|eot|ttf|woff2)$/,
        exclude : [ path.resolve(__dirname, 'lease') ],
        loader : 'url?limit=10000&name=[sha512:hash:base64:7].[ext]',
      },

      // lease assets (isomorphic)
      {
        test : isomorphicToolsPlugin.regular_expression('styles'),
        include : [ path.resolve(__dirname, 'lease') ],
        loader : ExtractTextPlugin.extract('css!autoprefixer?browsers=Chrome >= 13!sass'),
      },
      {
        test : isomorphicToolsPlugin.regular_expression('images'),
        include : [ path.resolve(__dirname, 'lease') ],
        loader : 'file?name=[sha512:hash:base64:7].[ext]',
      },
      {
        test : isomorphicToolsPlugin.regular_expression('fonts'),
        include : [ path.resolve(__dirname, 'lease') ],
        loader : 'url',
      },
    ],
  },
};

```

**Comment by TrySound** [comment]
@mattludwigs Do you have stack trace?

**Comment by mattludwigs** [comment]
```
ModuleBuildError: Module build failed: ModuleBuildError: Module build failed: TypeError: Cannot read property 'constructor' of null
    at clone (/home/runner/cahatlas.com/node_modules/postcss-merge-rules/dist/lib/clone.js:12:25)
    at clone (/home/runner/cahatlas.com/node_modules/postcss-merge-rules/dist/lib/clone.js:29:25)
    at clone (/home/runner/cahatlas.com/node_modules/postcss-merge-rules/dist/lib/clone.js:29:25)
    at /home/runner/cahatlas.com/node_modules/postcss-merge-rules/dist/lib/clone.js:26:24
    at Array.map (native)
    at clone (/home/runner/cahatlas.com/node_modules/postcss-merge-rules/dist/lib/clone.js:25:31)
    at partialMerge (/home/runner/cahatlas.com/node_modules/postcss-merge-rules/dist/index.js:105:48)
    at /home/runner/cahatlas.com/node_modules/postcss-merge-rules/dist/index.js:184:17
    at /home/runner/cahatlas.com/node_modules/postcss/lib/container.js:115:34
    at /home/runner/cahatlas.com/node_modules/postcss/lib/container.js:73:26
    at Root.each (/home/runner/cahatlas.com/node_modules/postcss/lib/container.js:60:22)
    at Root.walk (/home/runner/cahatlas.com/node_modules/postcss/lib/container.js:72:21)
    at Root.walkRules (/home/runner/cahatlas.com/node_modules/postcss/lib/container.js:113:25)
    at /home/runner/cahatlas.com/node_modules/postcss-merge-rules/dist/index.js:190:13
    at LazyResult.run (/home/runner/cahatlas.com/node_modules/postcss/lib/lazy-result.js:206:20)
    at /home/runner/cahatlas.com/node_modules/postcss/lib/lazy-result.js:120:37
    at LazyResult.asyncTick (/home/runner/cahatlas.com/node_modules/postcss/lib/lazy-result.js:134:15)
    at /home/runner/cahatlas.com/node_modules/postcss/lib/lazy-result.js:132:27
    at LazyResult.asyncTick (/home/runner/cahatlas.com/node_modules/postcss/lib/lazy-result.js:134:15)
    at /home/runner/cahatlas.com/node_modules/postcss/lib/lazy-result.js:132:27
    at LazyResult.asyncTick (/home/runner/cahatlas.com/node_modules/postcss/lib/lazy-result.js:134:15)
    at /home/runner/cahatlas.com/node_modules/postcss/lib/lazy-result.js:132:27
    at LazyResult.asyncTick (/home/runner/cahatlas.com/node_modules/postcss/lib/lazy-result.js:134:15)
    at /home/runner/cahatlas.com/node_modules/postcss/lib/lazy-result.js:132:27
    at LazyResult.asyncTick (/home/runner/cahatlas.com/node_modules/postcss/lib/lazy-result.js:134:15)
    at /home/runner/cahatlas.com/node_modules/postcss/lib/lazy-result.js:132:27
    at LazyResult.asyncTick (/home/runner/cahatlas.com/node_modules/postcss/lib/lazy-result.js:134:15)
    at /home/runner/cahatlas.com/node_modules/postcss/lib/lazy-result.js:132:27
    at LazyResult.asyncTick (/home/runner/cahatlas.com/node_modules/postcss/lib/lazy-result.js:134:15)
    at /home/runner/cahatlas.com/node_modules/postcss/lib/lazy-result.js:132:27
    at DependenciesBlock.onModuleBuildFailed (/home/runner/cahatlas.com/node_modules/webpack-core/lib/NormalModuleMixin.js:315:19)
    at nextLoader (/home/runner/cahatlas.com/node_modules/webpack-core/lib/NormalModuleMixin.js:270:31)
    at /home/runner/cahatlas.com/node_modules/webpack-core/lib/NormalModuleMixin.js:292:15
    at context.callback (/home/runner/cahatlas.com/node_modules/webpack-core/lib/NormalModuleMixin.js:148:14)
    at Object.<anonymous> (/home/runner/cahatlas.com/node_modules/css-loader/lib/loader.js:32:18)
    at /home/runner/cahatlas.com/node_modules/css-loader/lib/processCss.js:211:3
    at DependenciesBlock.onModuleBuildFailed (/home/runner/cahatlas.com/node_modules/webpack-core/lib/NormalModuleMixin.js:315:19)
    at DependenciesBlock.<anonymous> (/home/runner/cahatlas.com/node_modules/webpack-core/lib/NormalModuleMixin.js:228:39)
    at context.callback (/home/runner/cahatlas.com/node_modules/webpack-core/lib/NormalModuleMixin.js:148:14)
    at Object.<anonymous> (/home/runner/cahatlas.com/node_modules/extract-text-webpack-plugin/loader.js:82:20)
    at Compiler.<anonymous> (/home/runner/cahatlas.com/node_modules/webpack/lib/Compiler.js:204:18)
    at Compiler.<anonymous> (/home/runner/cahatlas.com/node_modules/webpack/lib/Compiler.js:395:18)
    at /home/runner/cahatlas.com/node_modules/tapable/lib/Tapable.js:99:11
    at Compilation.<anonymous> (/home/runner/cahatlas.com/node_modules/webpack/lib/Compilation.js:433:11)
    at errorAndCallback (/home/runner/cahatlas.com/node_modules/webpack/lib/Compilation.js:340:3)
    at Compilation.<anonymous> (/home/runner/cahatlas.com/node_modules/webpack/lib/Compilation.js:400:12)
    at /home/runner/cahatlas.com/node_modules/webpack/lib/Compilation.js:123:4
    at Array.forEach (native)
    at callback (/home/runner/cahatlas.com/node_modules/webpack/lib/Compilation.js:122:12)
    at Compilation.<anonymous> (/home/runner/cahatlas.com/node_modules/webpack/lib/Compilation.js:137:11)
    at DependenciesBlock.<anonymous> (/home/runner/cahatlas.com/node_modules/webpack/lib/NormalModule.js:85:18)
    at DependenciesBlock.onModuleBuildFailed (/home/runner/cahatlas.com/node_modules/webpack-core/lib/NormalModuleMixin.js:315:10)
    at nextLoader (/home/runner/cahatlas.com/node_modules/webpack-core/lib/NormalModuleMixin.js:270:31)
    at /home/runner/cahatlas.com/node_modules/webpack-core/lib/NormalModuleMixin.js:292:15
    at context.callback (/home/runner/cahatlas.com/node_modules/webpack-core/lib/NormalModuleMixin.js:148:14)
    at Object.<anonymous> (/home/runner/cahatlas.com/node_modules/css-loader/lib/loader.js:32:18)
    at /home/runner/cahatlas.com/node_modules/css-loader/lib/processCss.js:211:3
make: *** [build] Error 1
```

**Comment by TrySound** [comment]
@mattludwigs Share please minimal css code where use reproduce it.

**Comment by mattludwigs** [comment]
@TrySound I have no idea where the css issue would or even could be in the project. Do you believe there is a css issue that could be causing this?

**Comment by TrySound** [comment]
@mattludwigs I know how to fix but need to add test for this case.

**Comment by mattludwigs** [comment]
@TrySound do you need the proble

**Comment by mattludwigs** [comment]
sorry wrong button, one second

**Comment by mattludwigs** [comment]
@TrySound do you need the css that is wrong, or just some css?

**Comment by TrySound** [comment]
@mattludwigs css which reproduce this error.

**Comment by mattludwigs** [comment]
@TrySound Okay, I will look for it, but I will need to some digging around the css files.

**Comment by mattludwigs** [comment]
@TrySound I found the issue. It has to do with the not putting quotes here:

```
font-family: FontAwesome;
```

I guess autoprefixer updated a few hours ago that made custom fonts need quotes.

Thank you for you help on this issue.

However, do you think postcss should be doing a `null` check on `obj` before trying to call the method?

**Comment by TrySound** [comment]
@mattludwigs It's cssnano issue I think (`node_modules/postcss-merge-rules/dist/lib/clone.js`).

**Comment by TrySound** [comment]
Try to pass `mergeRules: false` option.

**Comment by mattludwigs** [comment]
@TrySound trying to figure out where `mergeRules: false` should go, any suggestions?

**Comment by TrySound** [comment]
@mattludwigs Never used webpack. Maybe `css-loader?-merge-rules`
https://github.com/webpack/css-loader

**Comment by mattludwigs** [comment]
@TrySound looks like cssnano 3.5.0 broken our build
https://github.com/ben-eb/cssnano/releases
We were on 3.4.0, and they release 3.5.0 about 5 hours ago when our builds stopped working.

**Comment by TrySound** [comment]
@mattludwigs  There was 3.5.1 release just now. Try to reinstall.

**Comment by mattludwigs** [comment]
@TrySound that did not fix it unfortunately.

**Comment by mattludwigs** [comment]
@TrySound, @ben-eb  I am thinking this might be a compound issue between cssnano and postcss packages.

We have shrink wrapped our production environment that uses cssnano 3.4.0 and the build works there.

But it does not work with cssnano 3.5.x. I am not sure exactly which package the issue is falls in or if it is between cssnano or postcss (or even another post css package).

I am noticing there is never any checks on the `obj` to make it is not `null` or an empty object which either case can lead to errors.

I did see:

```
if (typeof obj !== "object")
```
somewhere in these files, but `typeof null` is `"object"`.

**Comment by TrySound** [comment]
@mattludwigs Can you give us all css from your build? We can try to find the problem.

**Comment by ben-eb** [comment]
For what it's worth, postcss-merge-rules hasn't been updated since last December. Would appreciate some test case that can reproduce the problem so that we can ensure that it doesn't happen again.

**Comment by jwdotjs** [comment]
Hey all,

On Matt's team and we have a small sample. I'm not sure if it's relevant or not but the original code here fails to build:


```

$theme-style: "rounded";
$theme-type: "material-design";

.md-shadow-z-2 {
  box-shadow: 0 3px 6px rgba(0, 0, 0, 0.16), 0 3px 6px rgba(0, 0, 0, 0.22);
}

$general-border-radius: 4px !default;


@mixin ease-out($duration: 450ms, $property: all, $delay: 0ms) {
  transition: $property $duration cubic-bezier(0.23, 1, 0.32, 1) $delay;
}

@mixin opacity($value, $important: "") {
  opacity: $value #{$important};
  filter: alpha(opacity=#{$value * 100}) #{$important};
}

@if $theme-type == "material-design" {
  .dropdown-menu {
    @extend .md-shadow-z-2-i;
    border: 0 !important;
    border-radius: $general-border-radius !important;
    margin: 0;
    &:before,
    &:after {
      display: none !important;
    }
  }
  .btn-group {
    > .dropdown-menu {
      @extend .md-shadow-z-2-i;
      @include opacity(0);
      margin-top: 0px;
    }
    &.dropup {
      > .dropdown-menu {
        margin-top: 0px;
        margin-bottom: 0px;
      }
    }
  }
  .btn-group.open {
    > .dropdown-menu {
      @include ease-out(1500ms, opacity, 0.1ms);
      @include opacity(1);
    }
  }
}

```

and commenting out the `@if` at the bottom of the file will allow it to build.

Does that help?

**Comment by jwdotjs** [comment]
Our builds started failing 6 hours ago previous to that ~6 hour mark, the builds were passing. 

```
diff --git a/npm-shrinkwrap.json b/npm-shrinkwrap.json
index 427fdcd..e7fb2c6 100644
--- a/npm-shrinkwrap.json
+++ b/npm-shrinkwrap.json
@@ -4629,12 +4629,12 @@
     },
     "postcss-calc": {
       "version": "5.2.0",
-      "from": "postcss-calc@>=5.2.0 <6.0.0",
+      "from": "postcss-calc@>=5.0.0 <6.0.0",
       "resolved": "http://registry.npmjs.org/postcss-calc/-/postcss-calc-5.2.0.tgz"
     },
     "postcss-colormin": {
       "version": "2.1.8",
-      "from": "postcss-colormin@>=2.1.8 <3.0.0",
+      "from": "postcss-colormin@>=2.1.7 <3.0.0",
       "resolved": "http://registry.npmjs.org/postcss-colormin/-/postcss-colormin-2.1.8.tgz"
     },
     "postcss-convert-values": {
@@ -4643,24 +4643,24 @@
       "resolved": "http://registry.npmjs.org/postcss-convert-values/-/postcss-convert-values-2.3.4.tgz"
     },
     "postcss-discard-comments": {
-      "version": "2.0.4",
-      "from": "postcss-discard-comments@>=2.0.4 <3.0.0",
-      "resolved": "https://registry.npmjs.org/postcss-discard-comments/-/postcss-discard-comments-2.0.4.tgz"
+      "version": "2.0.3",
+      "from": "postcss-discard-comments@>=2.0.2 <3.0.0",
+      "resolved": "http://registry.npmjs.org/postcss-discard-comments/-/postcss-discard-comments-2.0.3.tgz"
     },
     "postcss-discard-duplicates": {
-      "version": "2.0.1",
-      "from": "postcss-discard-duplicates@>=2.0.1 <3.0.0",
-      "resolved": "https://registry.npmjs.org/postcss-discard-duplicates/-/postcss-discard-duplicates-2.0.1.tgz"
+      "version": "2.0.0",
+      "from": "postcss-discard-duplicates@>=2.0.0 <3.0.0",
+      "resolved": "http://registry.npmjs.org/postcss-discard-duplicates/-/postcss-discard-duplicates-2.0.0.tgz"
     },
     "postcss-discard-empty": {
-      "version": "2.0.1",
-      "from": "postcss-discard-empty@>=2.0.1 <3.0.0",
-      "resolved": "https://registry.npmjs.org/postcss-discard-empty/-/postcss-discard-empty-2.0.1.tgz"
+      "version": "2.0.0",
+      "from": "postcss-discard-empty@>=2.0.0 <3.0.0",
+      "resolved": "http://registry.npmjs.org/postcss-discard-empty/-/postcss-discard-empty-2.0.0.tgz"
     },
     "postcss-discard-unused": {
-      "version": "2.2.1",
-      "from": "postcss-discard-unused@>=2.2.1 <3.0.0",
-      "resolved": "https://registry.npmjs.org/postcss-discard-unused/-/postcss-discard-unused-2.2.1.tgz"
+      "version": "2.2.0",
+      "from": "postcss-discard-unused@>=2.1.0 <3.0.0",
+      "resolved": "http://registry.npmjs.org/postcss-discard-unused/-/postcss-discard-unused-2.2.0.tgz"
     },
     "postcss-filter-plugins": {
       "version": "2.0.0",
@@ -4668,9 +4668,9 @@
       "resolved": "http://registry.npmjs.org/postcss-filter-plugins/-/postcss-filter-plugins-2.0.0.tgz"
     },
     "postcss-merge-idents": {
-      "version": "2.1.5",
-      "from": "postcss-merge-idents@>=2.1.5 <3.0.0",
-      "resolved": "https://registry.npmjs.org/postcss-merge-idents/-/postcss-merge-idents-2.1.5.tgz"
+      "version": "2.1.4",
+      "from": "postcss-merge-idents@>=2.1.3 <3.0.0",
+      "resolved": "http://registry.npmjs.org/postcss-merge-idents/-/postcss-merge-idents-2.1.4.tgz"
     },
     "postcss-merge-longhand": {
       "version": "2.0.1",
@@ -4679,7 +4679,7 @@
     },
     "postcss-merge-rules": {
       "version": "2.0.3",
-      "from": "postcss-merge-rules@>=2.0.3 <3.0.0",
+      "from": "postcss-merge-rules@>=2.0.1 <3.0.0",
       "resolved": "http://registry.npmjs.org/postcss-merge-rules/-/postcss-merge-rules-2.0.3.tgz"
     },
     "postcss-message-helpers": {
@@ -4694,7 +4694,7 @@
     },
     "postcss-minify-gradients": {
       "version": "1.0.1",
-      "from": "postcss-minify-gradients@>=1.0.1 <2.0.0",
+      "from": "postcss-minify-gradients@>=1.0.0 <2.0.0",
       "resolved": "http://registry.npmjs.org/postcss-minify-gradients/-/postcss-minify-gradients-1.0.1.tgz"
     },
     "postcss-minify-params": {
@@ -4703,9 +4703,9 @@
       "resolved": "http://registry.npmjs.org/postcss-minify-params/-/postcss-minify-params-1.0.4.tgz"
     },
     "postcss-minify-selectors": {
-      "version": "2.0.4",
-      "from": "postcss-minify-selectors@>=2.0.4 <3.0.0",
-      "resolved": "https://registry.npmjs.org/postcss-minify-selectors/-/postcss-minify-selectors-2.0.4.tgz"
+      "version": "2.0.3",
+      "from": "postcss-minify-selectors@>=2.0.1 <3.0.0",
+      "resolved": "http://registry.npmjs.org/postcss-minify-selectors/-/postcss-minify-selectors-2.0.3.tgz"
     },
     "postcss-modules-extract-imports": {
       "version": "1.0.0",
@@ -4733,19 +4733,19 @@
       "resolved": "http://registry.npmjs.org/postcss-normalize-charset/-/postcss-normalize-charset-1.1.0.tgz"
     },
     "postcss-normalize-url": {
-      "version": "3.0.7",
-      "from": "postcss-normalize-url@>=3.0.7 <4.0.0",
-      "resolved": "https://registry.npmjs.org/postcss-normalize-url/-/postcss-normalize-url-3.0.7.tgz"
+      "version": "3.0.5",
+      "from": "postcss-normalize-url@>=3.0.4 <4.0.0",
+      "resolved": "http://registry.npmjs.org/postcss-normalize-url/-/postcss-normalize-url-3.0.5.tgz"
     },
     "postcss-ordered-values": {
-      "version": "2.1.0",
-      "from": "postcss-ordered-values@>=2.1.0 <3.0.0",
-      "resolved": "https://registry.npmjs.org/postcss-ordered-values/-/postcss-ordered-values-2.1.0.tgz"
+      "version": "2.0.2",
+      "from": "postcss-ordered-values@>=2.0.2 <3.0.0",
+      "resolved": "http://registry.npmjs.org/postcss-ordered-values/-/postcss-ordered-values-2.0.2.tgz"
     },
     "postcss-reduce-idents": {
-      "version": "2.2.2",
-      "from": "postcss-reduce-idents@>=2.2.2 <3.0.0",
-      "resolved": "https://registry.npmjs.org/postcss-reduce-idents/-/postcss-reduce-idents-2.2.2.tgz"
+      "version": "2.2.1",
+      "from": "postcss-reduce-idents@>=2.2.1 <3.0.0",
+      "resolved": "http://registry.npmjs.org/postcss-reduce-idents/-/postcss-reduce-idents-2.2.1.tgz"
     },
     "postcss-reduce-transforms": {
       "version": "1.0.3",
@@ -4759,18 +4759,18 @@
     },
     "postcss-selector-parser": {
       "version": "1.3.1",
-      "from": "postcss-selector-parser@>=1.3.1 <2.0.0",
+      "from": "postcss-selector-parser@>=1.3.0 <2.0.0",
       "resolved": "http://registry.npmjs.org/postcss-selector-parser/-/postcss-selector-parser-1.3.1.tgz"
     },
     "postcss-svgo": {
       "version": "2.1.1",
-      "from": "postcss-svgo@>=2.1.1 <3.0.0",
+      "from": "postcss-svgo@>=2.0.4 <3.0.0",
       "resolved": "http://registry.npmjs.org/postcss-svgo/-/postcss-svgo-2.1.1.tgz"
     },
     "postcss-unique-selectors": {
-      "version": "2.0.2",
-      "from": "postcss-unique-selectors@>=2.0.2 <3.0.0",
-      "resolved": "https://registry.npmjs.org/postcss-unique-selectors/-/postcss-unique-selectors-2.0.2.tgz"
+      "version": "2.0.1",
+      "from": "postcss-unique-selectors@>=2.0.1 <3.0.0",
+      "resolved": "http://registry.npmjs.org/postcss-unique-selectors/-/postcss-unique-selectors-2.0.1.tgz"
     },
     "postcss-value-parser": {
       "version": "3.2.3",
@@ -4779,7 +4779,7 @@
     },
     "postcss-zindex": {
       "version": "2.0.1",
-      "from": "postcss-zindex@>=2.0.1 <3.0.0",
+      "from": "postcss-zindex@>=2.0.0 <3.0.0",
       "resolved": "http://registry.npmjs.org/postcss-zindex/-/postcss-zindex-2.0.1.tgz"
     },
     "postgres-array": {
```

diff --git a/npm-shrinkwrap.json b/npm-shrinkwrap.json
index e7fb2c6..e400330 100644
--- a/npm-shrinkwrap.json
+++ b/npm-shrinkwrap.json
@@ -1032,9 +1032,9 @@
       "resolved": "http://registry.npmjs.org/cssesc/-/cssesc-0.1.0.tgz"
     },
     "cssnano": {
-      "version": "3.5.1",
+      "version": "3.4.0",
       "from": "cssnano@>=2.6.1 <4.0.0",
-      "resolved": "https://registry.npmjs.org/cssnano/-/cssnano-3.5.1.tgz"
+      "resolved": "http://registry.npmjs.org/cssnano/-/cssnano-3.4.0.tgz"
     },
     "csso": {
       "version": "1.4.4",


Somewhere in the `-` is the broken package(s) and the `+` versions fix the build. It seems to be more of a combination of the packages vs any one specific package from what we can tell so far.

**Comment by TrySound** [comment]
@mattludwigs @jwdotjs Should be fixed in https://github.com/ben-eb/postcss-merge-rules/commit/b2c5eec39d7df83bb3c2213a8f35ce88b3d017a8

**Comment by yoyurec** [comment]
:+1:

**Comment by ai** [comment]
Fixed https://github.com/postcss/postcss/commit/8ae0b7c59c2e2bc0c3cd9ee4b0e91f35c2453769

**Comment by jwdotjs** [comment]
Just wanted to say we confirmed this creates passing builds for us and that we really appreciate your prompt response and support. Thank you everyone!

**Comment by ben-eb** [comment]
@jwdotjs You're welcome. :smiley:

**Comment by mattludwigs** [comment]
Yes, thank you all for your time and quick responses!

**Comment by nicolas-goudry** [comment]
This bug is still happening when you leave a whitespace at the end of a rule:

```css
.flex-example {
  display: flex;
  flex-flow: row wrap ;
  justify-content: flex-start;
  align-content: stretch;
  align-items: flex-start;
}
```

I have some CSS rookies in my team and just spent an hour digging around our codebase to understand it came from this mistyping… Any way to avoid build errors like this?

**Comment by ai** [comment]
Could you show full stacktrace?

**Comment by nicolas-goudry** [comment]
For sure!

```
ERROR in ./~/css-loader?sourceMap&-minimize&modules&importLoaders=1&localIdentName=[name]__[local]___[hash:base64:5]!./~/postcss-loader!./~/less-loader?sourceMap!./src/components/aw-components/aw-datagroup/aw-datagroup.less
Module build failed: TypeError: Cannot read property 'constructor' of null
    at clone (C:\Users\NGO\dev\analog-way\HTML5\webrcs-react-redux-starter-kit\node_modules\autoprefixer\lib\prefixer.js:13:21)
    at clone (C:\Users\NGO\dev\analog-way\HTML5\webrcs-react-redux-starter-kit\node_modules\autoprefixer\lib\prefixer.js:29:19)
    at clone (C:\Users\NGO\dev\analog-way\HTML5\webrcs-react-redux-starter-kit\node_modules\autoprefixer\lib\prefixer.js:29:19)
    at Function.Prefixer.clone (C:\Users\NGO\dev\analog-way\HTML5\webrcs-react-redux-starter-kit\node_modules\autoprefixer\lib\prefixer.js:62:16)
    at FlexFlow.Prefixer.clone (C:\Users\NGO\dev\analog-way\HTML5\webrcs-react-redux-starter-kit\node_modules\autoprefixer\lib\prefixer.js:110:23)
    at FlexFlow.Declaration.insert (C:\Users\NGO\dev\analog-way\HTML5\webrcs-react-redux-starter-kit\node_modules\autoprefixer\lib\declaration.js:105:30)
    at FlexFlow.Declaration.add (C:\Users\NGO\dev\analog-way\HTML5\webrcs-react-redux-starter-kit\node_modules\autoprefixer\lib\declaration.js:138:19)
    at FlexFlow.Prefixer.process (C:\Users\NGO\dev\analog-way\HTML5\webrcs-react-redux-starter-kit\node_modules\autoprefixer\lib\prefixer.js:102:18)
    at FlexFlow.Declaration.process (C:\Users\NGO\dev\analog-way\HTML5\webrcs-react-redux-starter-kit\node_modules\autoprefixer\lib\declaration.js:144:50)
    at C:\Users\NGO\dev\analog-way\HTML5\webrcs-react-redux-starter-kit\node_modules\autoprefixer\lib\processor.js:123:31
    at C:\Users\NGO\dev\analog-way\HTML5\webrcs-react-redux-starter-kit\node_modules\postcss\lib\container.js:94:28
    at C:\Users\NGO\dev\analog-way\HTML5\webrcs-react-redux-starter-kit\node_modules\postcss\lib\container.js:81:26
    at Rule.each (C:\Users\NGO\dev\analog-way\HTML5\webrcs-react-redux-starter-kit\node_modules\postcss\lib\container.js:68:22)
    at Rule.walk (C:\Users\NGO\dev\analog-way\HTML5\webrcs-react-redux-starter-kit\node_modules\postcss\lib\container.js:80:21)
    at C:\Users\NGO\dev\analog-way\HTML5\webrcs-react-redux-starter-kit\node_modules\postcss\lib\container.js:83:32
    at Root.each (C:\Users\NGO\dev\analog-way\HTML5\webrcs-react-redux-starter-kit\node_modules\postcss\lib\container.js:68:22)
 @ ./src/components/aw-components/aw-datagroup/aw-datagroup.less 4:14-295 13:2-17:4 14:20-301
```

**Comment by ai** [comment]
@nicolas-goudry could you create some small repo to reproduce error. I think it would be easy, but I can’t reproduce it in my repo.

**Comment by nicolas-goudry** [comment]
For sure, I'll do it tomorrow! I'll keep you updated when it's done. Thanks!

**Comment by ai** [comment]
@nicolas-goudry fixed https://github.com/postcss/autoprefixer/commit/f69d28b97ba10a7e252533d0a023913deef99072

Please wait for Autoprefixer release. It could take 1 week (sorry, I am on vacation :-P)

**Comment by nicolas-goudry** [comment]
Nice, thanks for the quick fix!

Have a good time on your vacation :)

**Comment by ai** [comment]
@nicolas-goudry released in 6.3.7
